# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecipeApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  # Pods for RecipeApp

  target 'RecipeAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
  end

  target 'RecipeAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
